### ISSUE TITLE
Black flash just before border fade in.

### ISSUE THREAD

**Issue by xenophile127** [marcrobledo/super-game-boy-border-converter#2]
There is a black flash before border fade in on a North American SNES and SGB.

What seems to be happening is the tiles and tile map are not switching instantly so an opaque tile is replacing the transparent one. Other borders seem to always use tile 0 as the transparent tile to avoid this issue.

**Comment by marcrobledo** [comment]
This is a very valuable find, thank you!
You should post it in https://github.com/gbdev/pandocs/issues as well, since this must be documented.

I've fixed this in 9b0fe71, so it forces the first tile to be the blank tile. Let me know if it works correctly now!

**Comment by xenophile127** [comment]
Verified fixed. Thank you.
